services:
  postgres:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"  

  app:
    depends_on: 
      - postgres
    build:
      context: . 
      dockerfile: ./app.Dockerfile
    ports:
      - "8000:8000" 

  crawly:
    depends_on: 
      - postgres
    build:
      context: . 
      dockerfile: ./crawly.Dockerfile


  